### ISSUE TITLE
Subscribing to prefix vs subscribing to event

### ISSUE THREAD

**Issue by arkgil** [elixir-telemetry/telemetry#1]
This is a follow-up to the discussion on the [Ecto mailing list](https://groups.google.com/forum/#!topic/elixir-ecto/F0SJKj2Mfak) and @josevalim's comment [here](https://github.com/arkgil/events/pull/3#issuecomment-411078995).

@GregMefford proposed that maybe instead of subscribing to prefixes of events like we do now, we should subscribe directly to event names which would allow us to perform a simple `:ets.lookup` to find matching handlers.

---

I really like the simplicity of the proposed approach. I think that we were considering it when discussing the initial implementation, and I'm not sure why we settled on the prefixes 🤔 

I think that the difference boils down to following: in place of

```elixir
Telemetry.attach(..., [:phoenix], ..., ...)
```

there would be

```elixir
Telemetry.attach(..., Phoenix.events(), ..., ...)
```

To me the second example looks much more readable and better expresses the intent (i.e. subscribing to all the events published by Phoenix). However, it has a limitation: Phoenix (or any other project which uses this library) would need to know all the event names at the time of attaching the handler. Let's imagine that Phoenix emits the event with the execution time of the controller action. With the prefixes, the event name could be dynamically constructed like:

```elixir
Telemetry.execute([:phoenix, :latency, YourApp.Controller, :show], 12.01])
```

With static event names we would need to use the event metadata:

```elixir
Telemetry.execute([:phoenix, :controller, :latency], 12.01,
                  %{controller: YouApp.Controller, action: :show})
```

What do you think?

/cc @josevalim @GregMefford @studzien @chrismccord @cloud8421

**Comment by josevalim** [comment]
Yup, I agree with everything you said. You are not supposed to have dynamic names in the first place, that's what metadata is for. The only thing to watch out for is this:

```elixir
Telemetry.attach(..., [:phoenix], ..., ...)
Telemetry.attach(..., Phoenix.events(), ..., ...)
```

The first receives an event name, the other receives a list of event names. It may be worth having `attach` and `attach_many`.

I also think with this we can simplify the codebase a lot, there is a notion of prefixes that we won 't care about anymore and we can settle simply on "event names".

**Comment by arkgil** [comment]
@josevalim oh, right, we would need another function for attaching to a list of event names.

One thing @studzien mentioned is that we won't know if the API is alright until it's used in the real project. But since this change will simplify the design, then it's probably worth going for it.

One more thing is that without prefixes event names could be anything. I'm not sure if we want to allow that because we might want to introduce prefixes later.

**Comment by josevalim** [comment]
> One thing @studzien mentioned is that we won't know if the API is alright until it's used in the real project. But since this change will simplify the design, then it's probably worth going for it.

Agreed!

> One more thing is that without prefixes event names could be anything.

Plus I think the original motivation for introducing event names as lists separated by atoms, was not prefixes, but it was because different tools use different "syntaxes" for prefixes, so we decided to go with a higher level data structure.

**Comment by arkgil** [comment]
> Plus I think the original motivation for introducing event names as lists separated by atoms, was not prefixes, but it was because different tools use different "syntaxes" for prefixes, so we decided to go with a higher level data structure.

Right, totally forgot about it! 😅

**Comment by GregMefford** [comment]
I think it doesn't hurt to define an event by a list of atoms. I hadn't even thought about that when I made the proposal mentioned above. I was thinking an event would just be like `:phoenix_controller_call` like [we have today](https://hexdocs.pm/phoenix/Phoenix.Endpoint.html#module-phoenix-default-events).

I could argue for either side of that decision, though. Having it as a list allows you to, for example, do `Enum.join(metric, ".")` to get a StatsD/Graphite-compatible metric name with dots in it. But the fact is that you'll probably end up pattern-matching the list anyway most of the time to pluck out and handle different things differently, so it might as well just be one atom that you pattern-match instead of a list.

To see a "real-world" example, here's how one could do Phoenix metrics-collection today using a StatsD/DataDog back-end: https://github.com/LeToteTeam/band/blob/master/lib/band/instrumenters/phoenix.ex
It turns out to be mostly just passing through the metric names, but there's also a little bit of fiddling we want to do for each different type. So at the end of the day, we'd probably pattern-match on the `[:phoenix, :controller, :call]` event literal anyway, so it might just as well have been `:phoenix_controller_call` that we're matching on. The only reason a list would be better is if we wanted to do something like match on `[:phoenix | event]` to do some kind of further processing, but that's going to depend heavily on the structure of the events that are available and I'm struggling to even think of an example where I'd want to do something like that.

The one thing I can think of is taking events from different services that are all sent to one generic Telemetry handler, and dispatching them to a more specific one. In that case, though, it would probably make more sense to just configure them to get directly dispatched to the more-specific handler.

**Comment by GregMefford** [comment]
I'll also say that we should talk about what telemetry is being proposed because, as we know, naming things is both hard and important. If we have something called `[:phoenix, :controller, :latency]`, for example, would that telemetry fire _before_ the controller is called as well as _after_ (to allow for tracing), or only after? It would be great if we had consistent names for things that would be called before and after a relevant block of code.

Maybe something like:
`[:phoenix, :controller, :before]`
`[:phoenix, :controller, :after]`
`[:phoenix, :view, :before]`
`[:phoenix, :view, :after]`

Obviously, the latency metrics would only be populated (as metadata, probably) on the `:after` ones.

**Comment by josevalim** [comment]
> I'll also say that we should talk about what telemetry is being proposed because, as we know, naming things is both hard and important.

That will depend on the library using telemetry but yes, phoenix will likely have a before and after event. I guess with time we can provide a guidelines on how to best write events.

> So at the end of the day, we'd probably pattern-match on the [:phoenix, :controller, :call] event literal anyway

Because the dispatch is responsibility of telemetry, you most likely won't be pattern matching on it directly. Just subscribe to it. But yes, the advantage of a list of atoms is just the explicit hierarchy. You can't assume the hierarchy is on the underscore, as this would be ambiguous on library names such as `:gen_stage`.

**Comment by GregMefford** [comment]
> That will depend on the library using telemetry

Ah, I was assuming that this Telemetry library is just for (or at least primarily designed for) Phoenix, given that it's in the `phoenixframework` organization. That was also confusing me about how this library would be applied to Ecto. That clears things up if this is really more of a generic Elixir library for standardizing tracing and metrics hooks in various libraries.

> Because the dispatch is responsibility of telemetry, you most likely won't be pattern matching on it directly. Just subscribe to it.

Right, so if I subscribe to it by doing something like:

```elixir
Telemetry.attach(my_handler_id, [:phoenix, :controller, :before], MyTracer, :phoenix_controller_before)
```

it really turns out to be identical in practice if the API looks like:

```elixir
Telemetry.attach(my_handler_id, :phoenix_controller_before, MyTracer, :phoenix_controller_before)
```

Either way, I'm going to get `MyTracer.phoenix_controller_before` called in my callback/behaviour module, with the same arguments.

**Comment by josevalim** [comment]
> That clears things up if this is really more of a generic Elixir library for standardizing tracing and metrics hooks in various libraries.

Yes, precisely!

**Comment by arkgil** [comment]
Yeah, we should probably add at least short description to the README 😅
